apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  namespace: ecommerce-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: ecommerce-consumer:local
        imagePullPolicy: Never
        envFrom:
        - configMapRef:
            name: app-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"