apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: ecommerce-platform
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      # Prometheus lui-même
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      # Redpanda (metrics admin sur 9644)
      - job_name: 'redpanda'
        static_configs:
          - targets: ['redpanda-0.redpanda-service:9644']

      # Kube-State-Metrics (expose /metrics sur 8080)
      - job_name: 'kube-state-metrics'
        static_configs:
          - targets: ['kube-state-metrics.kube-system.svc:8080']

      # Découverte des Pods du namespace (optionnel)
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names: ['ecommerce-platform']
        # (Optionnel) Ne scraper que les pods annotés :
        # relabel_configs:
        #   - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        #     action: keep
        #     regex: true
        #   - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        #     action: replace
        #     target_label: __metrics_path__
        #     regex: (.+)
        #   - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        #     action: replace
        #     regex: (.+):(?:\d+);(\d+)
        #     replacement: $1:$2
        #     target_label: __address__
