apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: ecommerce-platform
---
# Droits de lecture sur Pods/Endpoints/Services dans le namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-discovery
  namespace: ecommerce-platform
rules:
- apiGroups: [""]
  resources: ["pods", "endpoints", "services"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-discovery
  namespace: ecommerce-platform
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: ecommerce-platform
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-discovery
---
# Patch du Deployment pour utiliser cette SA
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: ecommerce-platform
spec:
  template:
    spec:
      serviceAccountName: prometheus
