apiVersion: v1
kind: Service
metadata:
  name: redpanda-service
  namespace: ecommerce-platform
spec:
  selector:
    app: redpanda
  clusterIP: None
  ports:
  - port: 9092
    name: kafka
  - port: 8081
    name: schema
  - port: 9644
    name: admin

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redpanda
  namespace: ecommerce-platform
spec:
  serviceName: redpanda-service
  replicas: 1
  selector:
    matchLabels:
      app: redpanda
  template:
    metadata:
      labels:
        app: redpanda
    spec:
      containers:
      - name: redpanda
        image: docker.redpanda.com/redpandadata/redpanda:v23.2.18
        command:
        - rpk
        - redpanda
        - start
        - --overprovisioned
        - --smp=1
        - --memory=512M
        - --reserve-memory=0M
        - --kafka-addr
        - internal://0.0.0.0:9092
        - --advertise-kafka-addr
        - internal://redpanda-0.redpanda-service.ecommerce-platform.svc.cluster.local:9092
        - --pandaproxy-addr
        - internal://0.0.0.0:8082
        - --advertise-pandaproxy-addr
        - internal://redpanda-0.redpanda-service.ecommerce-platform.svc.cluster.local:8082
        - --schema-registry-addr
        - internal://0.0.0.0:8081
        - --rpc-addr
        - redpanda-0.redpanda-service.ecommerce-platform.svc.cluster.local:33145
        - --advertise-rpc-addr
        - redpanda-0.redpanda-service.ecommerce-platform.svc.cluster.local:33145
        ports:
        - containerPort: 9092
          name: kafka
        - containerPort: 8081
          name: schema
        - containerPort: 8082
          name: proxy
        - containerPort: 9644
          name: admin
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        volumeMounts:
        - name: redpanda-data
          mountPath: /var/lib/redpanda/data
  volumeClaimTemplates:
  - metadata:
      name: redpanda-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 5Gi
  