apiVersion: v1
kind: Namespace
metadata:
  name: ecommerce-platform

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: streamlit-data-pvc
  namespace: ecommerce-platform
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit
  namespace: ecommerce-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
      - name: streamlit
        image: streamlit-ecommerce:latest  # ← IMAGE LOCALE
        imagePullPolicy: Never  # ← IMPORTANT pour Docker Desktop
        ports:
        - containerPort: 8501
          name: http
        env:
        - name: KAFKA_BROKERS
          value: "redpanda-service:9092"
        - name: KAFKA_TOPIC_VIEWS
          value: "product_views"
        - name: KAFKA_TOPIC_EVENTS
          value: "events_app"
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: TZ
          value: "Europe/Paris"
        volumeMounts:
        - name: data
          mountPath: /app/data
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /_stcore/health
            port: http
          initialDelaySeconds: 20
          periodSeconds: 20
          timeoutSeconds: 2
          failureThreshold: 6
        readinessProbe:
          httpGet:
            path: /_stcore/health
            port: http
          initialDelaySeconds: 8
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 6
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: streamlit-data-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
  namespace: ecommerce-platform
spec:
  type: LoadBalancer
  selector:
    app: streamlit
  ports:
  - protocol: TCP
    port: 8501
    targetPort: 8501