apiVersion: v1
kind: Namespace
metadata:
  name: ecommerce-platform

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit
  namespace: ecommerce-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      # Créer le dossier data au démarrage
      initContainers:
      - name: init-data-dir
        image: busybox
        command: ['sh', '-c', 'mkdir -p /data && chmod 777 /data']
        volumeMounts:
        - name: data-dir
          mountPath: /data
      
      containers:
      - name: streamlit
        image: streamlit-ecommerce:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8501
          name: http
        env:
        - name: KAFKA_BROKERS
          value: "redpanda-service:9092"
        - name: KAFKA_TOPIC_VIEWS
          value: "product_views"
        - name: KAFKA_TOPIC_EVENTS
          value: "events_app"
        - name: PYTHONUNBUFFERED
          value: "1"
        volumeMounts:
        # Dossier data vide
        - name: data-dir
          mountPath: /app/data
        # CSV depuis ConfigMap
        - name: csv-data
          mountPath: /app/data/produit.csv
          subPath: produit.csv
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /_stcore/health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /_stcore/health
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
      
      volumes:
      # Volume temporaire pour /app/data
      - name: data-dir
        emptyDir: {}
      # ConfigMap pour le CSV
      - name: csv-data
        configMap:
          name: produit-csv

---
apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
  namespace: ecommerce-platform
spec:
  type: LoadBalancer
  selector:
    app: streamlit
  ports:
  - protocol: TCP
    port: 8501
    targetPort: 8501
