# monitoring/prometheus/prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus lui-même
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Redpanda metrics
  - job_name: 'redpanda'
    static_configs:
      - targets: ['redpanda:9644']

  # Application metrics (si implémentées)
  - job_name: 'producer'
    static_configs:
      - targets: ['producer:8000']

  - job_name: 'consumer'
    static_configs:
      - targets: ['consumer:8000']